Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,32 +1,23 @@
 name: CI/CD
 
-# ⬇️  Modify the fields marked with ⬇️ to fit your project, and create any secrets that are referenced.
-# https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets
 env:
-  # ⬇️ EDIT with your registry and registry path.
-  REGISTRY: quay.io/${{ secrets.DOCKERHUB_USERNAME }}
-  # ⬇️ EDIT with your registry username.
-  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
+  # Using Quay.io
+  REGISTRY: quay.io/dabreadman
+  REGISTRY_USER: dabreadman
   REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
 
-  # ⬇️ EDIT to log into your OpenShift cluster and set up the context.
-  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
+  # OpenShift Token
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
-
-  # ⬇️ EDIT with the port your application should be accessible on.
   APP_PORT: 8080
-  OPENSHIFT_NAMESPACE: "dabreadman-code"
+  OPENSHIFT_NAMESPACE: "dabreadman-staging"
 
-  # If you wish to manually provide the APP_NAME and TAG, set them here, otherwise they will be auto-detected.
   APP_NAME: "covid-app"
   TAG: ""
 
-
 on:
-  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
-    push:
-    workflow_dispatch:
+  push:
+  workflow_dispatch:
 
 jobs:
   openshift-ci-cd:
@@ -38,89 +29,86 @@ jobs:
     environment: production
 
     outputs:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
 
     steps:
-    - name: Check if secrets exists
-      uses: actions/github-script@v3
-      with:
-        script: |
-          const secrets = {
-            REGISTRY_PASSWORD: `${{ secrets.REGISTRY_PASSWORD }}`,
-            OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
-            OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
-          };
+      - name: Check if secrets exists
+        uses: actions/github-script@v3
+        with:
+          script: |
+            const secrets = {
+              REGISTRY_PASSWORD: `${{ secrets.REGISTRY_PASSWORD }}`,
+              OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
+              OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
+            };
 
-          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
-            if (value.length === 0) {
-              core.warning(`Secret "${name}" is not set`);
-              return true;
+            const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
+              if (value.length === 0) {
+                core.warning(`Secret "${name}" is not set`);
+                return true;
+              }
+              core.info(`✔️ Secret "${name}" is set`);
+              return false;
+
+            });
+
+            if (missingSecrets.length > 0) {
+              core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
+                "You can add it using:\n" +
+                "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
+                "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
+                "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
             }
-            core.info(`✔️ Secret "${name}" is set`);
-            return false;
+            else {
+              core.info(`✅ All the required secrets are set`);
+            }
 
-          });
+      - uses: actions/checkout@v2
 
-          if (missingSecrets.length > 0) {
-            core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
-              "You can add it using:\n" +
-              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
-              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
-              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
-          }
-          else {
-            core.info(`✅ All the required secrets are set`);
-          }
+      - name: Determine app name
+        if: env.APP_NAME == ''
+        run: |
+          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
 
-    - uses: actions/checkout@v2
+      - name: Determine tag
+        if: env.TAG == ''
+        run: |
+          echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
 
-    - name: Determine app name
-      if: env.APP_NAME == ''
-      run: |
-        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
+      - name: Create Image
+        run: podman build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
 
-    - name: Determine tag
-      if: env.TAG == ''
-      run: |
-        echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
+      - name: Registry Autherisation
+        run: podman login -u ${{ env.REGISTRY_USERNAME }} -p ${{ env.REGISTRY_PASSWORD }} quay.io
+      - name: Push to registry
+        run: podman push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
 
-    - name: Create Image
-      run: podman build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
+      - name: Log in to OpenShift
+        uses: redhat-actions/oc-login@v1
+        with:
+          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+          insecure_skip_tls_verify: true
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
-    - name: Registry Autherisation
-      run: podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} quay.io 
-    - name: Push to registry
-      run: podman push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
+      - name: Create and expose app
+        id: deploy-and-expose
+        uses: redhat-actions/oc-new-app@v1
+        with:
+          app_name: ${{ env.APP_NAME }}
+          image: ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
+          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+          port: ${{ env.APP_PORT }}
 
-    # https://github.com/redhat-actions/oc-login#readme
-    - name: Log in to OpenShift
-      uses: redhat-actions/oc-login@v1
-      with:
-        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-        insecure_skip_tls_verify: true
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-
-    # This step should create a deployment, service, and route to run your app and expose it to the internet.
-    # https://github.com/redhat-actions/oc-new-app#readme
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ env.REGISTRY }}/${{ env.APP_NAME }}:${{ env.TAG }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
-
-    - name: View application route
-      run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-        echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
-        echo "==================================================================================="
-        echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
-      env:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      - name: View application route
+        run: |
+          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+          echo "======================== Your application is available at: ========================"
+          echo ${{ env.ROUTE }}
+          echo "==================================================================================="
+          echo
+          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+        env:
+          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
